# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data = pd.read_csv("../WeatherPy/output_data/cities.csv")
weather_data

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,Khatanga,71.9667,102.5000,56.10,76,100,8.93,RU,1629099479
1,1,Bhuj,23.2667,69.6667,91.67,45,46,11.99,IN,1629099479
2,2,Half Moon Bay,37.4636,-122.4286,67.82,87,1,0.00,US,1629099479
3,3,Albany,42.6001,-73.9662,58.39,91,96,2.98,US,1629099330
4,4,Norman Wells,65.2820,-126.8329,46.44,100,20,4.61,CA,1629099480
...,...,...,...,...,...,...,...,...,...,...
564,564,Santa María del Oro,25.9333,-105.3667,64.17,80,37,3.29,MX,1629099704
565,565,Ürümqi,43.8010,87.6005,68.95,60,0,4.47,CN,1629099704
566,566,Madimba,-10.4000,40.3333,78.12,69,20,25.32,TZ,1629099705
567,567,Ilebo,-4.3167,20.5833,91.26,33,48,4.21,CD,1629099705
568,568,Nísia Floresta,-6.0911,-35.2086,70.61,91,89,8.57,BR,1629099706

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps
gmaps.configure(api_key=g_key)

# Establish variables
locations = weather_data[["Lat", "Lng"]].astype(float)
humidity = weather_data["Humidity"].astype(float)
max_humidity = np.max(humidity)

In [4]:
# Create heatmap
fig = gmaps.figure(map_type='HYBRID')
heatmap_layer = gmaps.heatmap_layer(locations,
                                    weights = humidity,
                                    dissipating=False,
                                    max_intensity=max_humidity,
                                    point_radius=5)
fig.add_layer(heatmap_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
# Narrow down the cities to fit weather conditions
# Drop any rows with nulls
new_cities = weather_data.loc[(weather_data['Max Temp'] >= 70)
                                      & (weather_data['Max Temp'] <= 80)
                                      & (weather_data['Wind Speed'] <= 10)
                                      & (weather_data['Cloudiness'] <= 4)]
new_cities = new_cities.dropna(how = 'any')

new_cities

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
7,7,Busselton,-33.6500,115.3333,74.08,59,0,4.63,AU,1629099481
12,12,Adilcevaz,38.8039,42.7342,76.71,40,0,4.03,TR,1629099483
35,35,Aripuanã,-9.1667,-60.6333,70.00,58,0,1.03,BR,1629099492
52,52,Dengzhou,37.8086,120.7508,78.91,74,4,6.93,CN,1629099499
105,105,Arrondissement d'Ajaccio,42.0000,8.9167,79.29,47,0,5.75,FR,1629099520
128,128,Hendek,40.7994,30.7481,73.72,41,0,4.07,TR,1629099529
153,153,Elko,41.0002,-115.5012,71.64,17,0,5.99,US,1629099539
206,206,Freeport,40.6576,-73.5832,74.01,83,1,0.00,US,1629099394
213,213,Pec,42.6591,20.2883,75.49,29,0,3.98,XK,1629099562
249,249,Lata,40.1629,-8.3327,73.04,55,0,4.21,PT,1629099576
257,257,Irtyshskiy,58.3333,68.1333,77.77,41,1,4.18,RU,1629099579
319,319,Jacareacanga,-6.2222,-57.7528,70.93,88,4,1.63,BR,1629099605
320,320,Belyy Yar,53.6039,91.3903,75.09,33,0,4.47,RU,1629099605
346,346,Agnita,45.9667,24.6167,74.91,36,0,4.90,RO,1629099616
361,361,Zeya,53.7500,127.2667,79.56,48,4,1.97,RU,1629099621
363,363,Natal,-5.7950,-35.2094,70.45,88,0,6.91,BR,1629099580
379,379,Mkushi,-13.6202,29.3939,70.52,41,0,9.86,ZM,1629099630
404,404,Tutóia,-2.7619,-42.2744,75.94,88,3,8.34,BR,1629099640
427,427,Dixon,38.4455,-121.8233,78.98,53,1,4.61,US,1629099649
442,442,Jaru,-10.4389,-62.4664,73.38,49,0,2.35,BR,1629099655
474,474,Panjāb,34.3880,67.0233,73.62,8,0,7.43,AF,1629099668
483,483,Selikhino,50.3672,137.4996,76.14,62,3,5.86,RU,1629099672
487,487,Snyder,32.7179,-100.9176,75.34,73,1,5.75,US,1629099673
528,528,Pierre,44.3683,-100.3510,77.92,64,1,1.99,US,1629099690

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
# Store into variable named hotel_df
# Add a "Hotel Name" column to the DataFrame
hotel_df = new_cities
hotel_df['Hotel Name'] = ''

hotel_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
7,7,Busselton,-33.6500,115.3333,74.08,59,0,4.63,AU,1629099481,
12,12,Adilcevaz,38.8039,42.7342,76.71,40,0,4.03,TR,1629099483,
35,35,Aripuanã,-9.1667,-60.6333,70.00,58,0,1.03,BR,1629099492,
52,52,Dengzhou,37.8086,120.7508,78.91,74,4,6.93,CN,1629099499,
105,105,Arrondissement d'Ajaccio,42.0000,8.9167,79.29,47,0,5.75,FR,1629099520,
128,128,Hendek,40.7994,30.7481,73.72,41,0,4.07,TR,1629099529,
153,153,Elko,41.0002,-115.5012,71.64,17,0,5.99,US,1629099539,
206,206,Freeport,40.6576,-73.5832,74.01,83,1,0.00,US,1629099394,
213,213,Pec,42.6591,20.2883,75.49,29,0,3.98,XK,1629099562,
249,249,Lata,40.1629,-8.3327,73.04,55,0,4.21,PT,1629099576,
257,257,Irtyshskiy,58.3333,68.1333,77.77,41,1,4.18,RU,1629099579,
319,319,Jacareacanga,-6.2222,-57.7528,70.93,88,4,1.63,BR,1629099605,
320,320,Belyy Yar,53.6039,91.3903,75.09,33,0,4.47,RU,1629099605,
346,346,Agnita,45.9667,24.6167,74.91,36,0,4.90,RO,1629099616,
361,361,Zeya,53.7500,127.2667,79.56,48,4,1.97,RU,1629099621,
363,363,Natal,-5.7950,-35.2094,70.45,88,0,6.91,BR,1629099580,
379,379,Mkushi,-13.6202,29.3939,70.52,41,0,9.86,ZM,1629099630,
404,404,Tutóia,-2.7619,-42.2744,75.94,88,3,8.34,BR,1629099640,
427,427,Dixon,38.4455,-121.8233,78.98,53,1,4.61,US,1629099649,
442,442,Jaru,-10.4389,-62.4664,73.38,49,0,2.35,BR,1629099655,
474,474,Panjāb,34.3880,67.0233,73.62,8,0,7.43,AF,1629099668,
483,483,Selikhino,50.3672,137.4996,76.14,62,3,5.86,RU,1629099672,
487,487,Snyder,32.7179,-100.9176,75.34,73,1,5.75,US,1629099673,
528,528,Pierre,44.3683,-100.3510,77.92,64,1,1.99,US,1629099690,

In [7]:
# Set parameters to search for hotels with 5000 meters
# Hit the Google Places API for each city's coordinates
# Store the first Hotel result into the DataFrame

base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json'
params = {
    'keyword':'hotel',
    'radius': 5000,
    'key': g_key
}

# Iterate through pandas dataframe

for index, row in hotel_df.iterrows():

    # Hotel locations
    lat = row['Lat']
    lng = row['Lng']
    City_name = row['City']

    params['location'] = f"{lat},{lng}"

    # Assemble url and make API request
    response = requests.request('get', base_url, params=params).json()
    
    # Extract results
    results = response['results']
    
    # Save hotels to df
    try:
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        print(f"Closest hotel in {City_name} is {results[0]['name']}.")
        
    except (KeyError, IndexError):
        hotel_df.loc[index, 'Hotel Name'] = 'No hotels / missing data'
        print(f"No hotels within range of / missing data for {City_name}")

        
    print('----------------------------------------------------------------------')

No hotels within range of / missing data for Busselton
----------------------------------------------------------------------
No hotels within range of / missing data for Adilcevaz
----------------------------------------------------------------------
No hotels within range of / missing data for Aripuanã
----------------------------------------------------------------------
No hotels within range of / missing data for Dengzhou
----------------------------------------------------------------------
No hotels within range of / missing data for Arrondissement d'Ajaccio
----------------------------------------------------------------------
No hotels within range of / missing data for Hendek
----------------------------------------------------------------------
No hotels within range of / missing data for Elko
----------------------------------------------------------------------
No hotels within range of / missing data for Freeport
----------------------------------------------------------------------
No hotels within range of / missing data for Pec
----------------------------------------------------------------------
No hotels within range of / missing data for Lata
----------------------------------------------------------------------
No hotels within range of / missing data for Irtyshskiy
----------------------------------------------------------------------
No hotels within range of / missing data for Jacareacanga
----------------------------------------------------------------------
No hotels within range of / missing data for Belyy Yar
----------------------------------------------------------------------
No hotels within range of / missing data for Agnita
----------------------------------------------------------------------
No hotels within range of / missing data for Zeya
----------------------------------------------------------------------
No hotels within range of / missing data for Natal
----------------------------------------------------------------------
No hotels within range of / missing data for Mkushi
----------------------------------------------------------------------
No hotels within range of / missing data for Tutóia
----------------------------------------------------------------------
No hotels within range of / missing data for Dixon
----------------------------------------------------------------------
No hotels within range of / missing data for Jaru
----------------------------------------------------------------------
No hotels within range of / missing data for Panjāb
----------------------------------------------------------------------
No hotels within range of / missing data for Selikhino
----------------------------------------------------------------------
No hotels within range of / missing data for Snyder
----------------------------------------------------------------------
No hotels within range of / missing data for Pierre
----------------------------------------------------------------------

In [ ]:
# Fairly certain above code will work but google trial has run out and wants me to start being billed before it will run properly

In [8]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [9]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))